### ISSUE TITLE
GPLv2 not compatible with Apache License from libraries

### ISSUE THREAD

**Issue by dschuermann** [jfreax/OpenLaw#3]
Please consider switching from GPLv2 to GPLv3 as GPLv2 is not compatible with Licenses from your used libraries. This stops F-Droid from putting your app in their repo. See https://f-droid.org/forums/topic/openlaw/

**Comment by jfreax** [comment]
You are completely right. That has been on my todo list.
I’ve changed the license to GPL3

Thanks.
