### ISSUE TITLE
Weird problems when building app on your own

### ISSUE THREAD

**Issue by mvdan** [jfreax/OpenLaw#4]
Hello jfreax,

Since I cannot find your email address anywhere, I'm writing to you via a github issue :)

I come from F-Droid. We included and activated your app about a week ago. It builds fine, but some strange issues appear. The settings button doesn't work, with the following logcat:

```
D/SherlockFragmentActivity(10771): [onMenuItemSelected] featureId: 0, item: Einstellungen
D/ActionBarSherlock(10771): [dispatchOptionsItemSelected] item: Einstellungen
D/ActionBarSherlock(10771): [callbackOptionsItemSelected] item: Einstellungen
D/Watson  (10771): [onMenuItemSelected] featureId: 0, item: com.actionbarsherlock.internal.view.menu.MenuItemWrapper@41fa37d0
D/ActionBarSherlock(10771): [callbackOptionsItemSelected] returning true
D/ActionBarSherlock(10771): [dispatchOptionsItemSelected] returning true
D/SherlockFragmentActivity(10771): [onMenuItemSelected] returning true
```

Also, it sometimes crashes when pressing back (it just crashed on me when exiting the app):

```
E/AndroidRuntime(10406): java.lang.NullPointerException
E/AndroidRuntime(10406):    at de.jdsoft.law.LawTextFragment.getContext(LawTextFragment.java:233)
E/AndroidRuntime(10406):    at de.jdsoft.law.LawTextFragment.access$000(LawTextFragment.java:24)
E/AndroidRuntime(10406):    at de.jdsoft.law.LawTextFragment$2$1.run(LawTextFragment.java:112)
E/AndroidRuntime(10406):    at android.os.Handler.handleCallback(Handler.java:725)
E/AndroidRuntime(10406):    at android.os.Handler.dispatchMessage(Handler.java:92)
```

I haven't noticed any more issues, but there could be more. Basically, our build procedure for your app is quite strange because of the following reasons:
1. You don't provide a project.properties file, so we have to link to the libraries ourselves and make up a target (we used 18).
2. The android support jar you're using is very old! r7 should not be used. At least use r12 or r13 if you don't want to use r18.
3. You're using rather old versions of libraries. For example, you use ABS 4.2.0, while 4.4 is already out. This could be why the settings button doesn't work.

Well, you get why it's hard for us. If you tidied it up a bit and made the building process more clear, we would be able to follow your build instructions more easily and our apk wouldn't differ from yours that much.

If you have any questions or would like my help, don't hesitate to ask.

Regards.

**Comment by jfreax** [comment]
Hello,

at first: Thanks for your feedback! :+1: 

> The settings button doesn't work

Thats correct. There is no settings activity at the moment. I removed the button in version 0.6. I will implement this later.

> Also, it sometimes crashes when pressing back

Ok, that's wrong. Can you test it with the newest version and send me your logcat output again?

> build procedure for your app

Yeahh, thats because I have no clue how to make this right. Maven? Gradle? There are only problems with these tools. Or I am too dumb :/

> You don't provide a project.properties file, so we have to link to the libraries ourselves and make up a target (we used 18).

I added one. Don't know if it's correct.

> The android support jar you're using is very old! r7 should not be used. At least use r12 or r13 if you don't want to use r18.

Updated to version r13.

> You're using rather old versions of libraries.

Ok, I will update them, too.

> Well, you get why it's hard for us.

I hope its now a little bit easier for you. And I'll add anything necessary to make it even easier.

> If you have any questions or would like my help, don't hesitate to ask.

Thanks for your help. Very nice :)
What is the most common / easiest method to handle and update dependencies?

**Comment by mvdan** [comment]
> at first: Thanks for your feedback! 

Thank you for your quick reply and help.

> Thats correct. There is no settings activity at the moment. I removed the button in version 0.6. I will implement this later.

Ah, OK.

> Ok, that's wrong. Can you test it with the newest version and send me your logcat output again?

I will do.

> Yeahh, thats because I have no clue how to make this right. Maven? Gradle? There are only problems with these tools. Or I am too dumb :/

You are currently using Ant, which is what Eclipse, IntelliJ and others use. The new Android IDE uses Gradle, which in practice is about the same.

> I added one. Don't know if it's correct.

Seems OK. Why do you need the Google API, though? You don't seem to use Google Maps nor anything similar. The "android-17" target suits the project better.

> I hope its now a little bit easier for you. And I'll add anything necessary to make it even easier.

Thanks for your cooperation! :)

If you're using tags and keep the build process clean, it's perfect. I can't think of any other changes besides what I said above.

> Ok, I will update them, too.
> What is the most common / easiest method to handle and update dependencies?

You might want to use submodules. This would keep the repo size down, and it would be easier for you to keep track of lib versions and update them (see man git-submodule). For example, see how the owncloud guys link to actionbarsherlock: https://github.com/owncloud/android

Instead of having to copy the whole source code files, you only need to "git submodule add" and then you can checkout any tag or hash you want of the dependencies easily. Remember to add .gitmodules to the repo. As usual, the Git scm book will be of help: http://git-scm.com/book/en/Git-Tools-Submodules

**Comment by jfreax** [comment]
> Why do you need the Google API, though?

You are right, thats wrong. 

> You might want to use submodules.

Ohh yes. Submodules, I totally forgot these.
Added :)

Thank you!

**Comment by mvdan** [comment]
Hey! Big thumbs up about the many improvements :)

Just one last problem...

```
Unable to checkout 'f4c9a8c6f84a3af21f8d778e58bd66593ecedba6' in submodule path 'extern/android-async-http'
```

Even the web UI agrees with me:

https://github.com/loopj/android-async-http/tree/f4c9a8c6f84a3af21f8d778e58bd66593ecedba6

Where did you get the ref from?

**Comment by jfreax** [comment]
I committed something myself into these submodule - stupid gui and stupid me.
This should be fixed.

Aaaandd, thanks again :)

**Comment by mvdan** [comment]
Cool! As soon as you tag the next release we'll update it.
